/**
 * Pre-highlights the landing page's code samples.
 *
 * The samples are static, so highlighting them at build time keeps Shiki out of
 * the client bundle entirely. Re-run with `bun run highlight` after editing one.
 */
import { codeToHtml } from "shiki";

const SAMPLES = {
  install: {
    lang: "bash",
    code: ["$ bun create mirinjs my-app", "$ cd my-app && bun install", "$ bun run dev"].join("\n"),
  },
  router: {
    lang: "typescript",
    code: `import { rpc } from 'mirinjs/rpc'

export const router = rpc.router({
  greet: rpc.query(async (name: string) => \`Hello, \${name}!\`),
  tick: rpc.event<{ count: number }>(),
})

export type Router = typeof router`,
  },
  client: {
    lang: "typescript",
    code: `import { client } from 'mirinjs/client'
import type { Router } from '../main/rpc.ts'

export const api = client<Router>()

await api.greet('world')            // Promise<string>, inferred
api.tick.on(({ count }) => setTicks(count))`,
  },
  check: {
    lang: "bash",
    code: `$ bunx mirin check --scenario ./check.ts
# ✓ window ready — 1 of 1
# ✓ scenario — todo added, list length 1
# ✓ screenshot — w1.png
# ✓ no renderer errors
#   .mirin/dev/20260821-1042/events.jsonl`,
  },
} as const;

const entries: string[] = [];
for (const [name, { lang, code }] of Object.entries(SAMPLES)) {
  const html = await codeToHtml(code, { lang, theme: "vesper" });
  entries.push(`  ${name}: ${JSON.stringify(html)},`);
}

await Bun.write(
  "src/generated/samples.ts",
  "// Generated by scripts/highlight-samples.ts — do not edit by hand.\n" +
    `export const SAMPLES = {\n${entries.join("\n")}\n} as const;\n\n` +
    "export type SampleName = keyof typeof SAMPLES;\n",
);
console.log(`highlighted ${Object.keys(SAMPLES).length} samples`);
